#!/bin/sh
# docker-entrypoint.sh
#
# Writes /usr/share/nginx/html/config.js from runtime configuration, then
# execs the CMD (nginx).  A single Docker image therefore works for every
# deployment — no rebuild required when config changes.
#
# Configuration priority (highest → lowest) for each key:
#   1. Environment variable  VITE_<KEY>
#   2. Docker secret file    /run/secrets/<KEY>   (key in UPPER_SNAKE_CASE)
#   3. Empty / null
#
# Example Docker secret names:  TMDB_READ_API_KEY  CORS_PROXY_URL  …
set -e

CONFIG_FILE="/usr/share/nginx/html/config.js"

# ── Helpers ───────────────────────────────────────────────────────────────────

# Read a value: env var takes precedence, then Docker secret file.
# Usage: read_val "$VITE_FOO" "FOO"
read_val() {
  local env_val="$1"
  local secret_name="$2"
  local secret_file="/run/secrets/${secret_name}"
  if [ -n "$env_val" ]; then
    printf '%s' "$env_val"
  elif [ -f "$secret_file" ]; then
    # Strip trailing newline that editors often add to secret files
    tr -d '\n' < "$secret_file"
  fi
}

# Output a JavaScript string literal ("value") or null when empty.
# Escapes backslashes and double-quotes to produce valid JS.
js_val() {
  local raw
  raw="$(read_val "$1" "$2")"
  if [ -n "$raw" ]; then
    printf '"%s"' "$(printf '%s' "$raw" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  else
    printf 'null'
  fi
}

# Output a JavaScript boolean (true/false).
js_bool() {
  local raw
  raw="$(read_val "$1" "$2")"
  case "$raw" in
    true | 1 | yes) printf 'true' ;;
    *) printf 'false' ;;
  esac
}

# ── Generate config.js ────────────────────────────────────────────────────────
{
  echo "// Runtime configuration — generated by docker-entrypoint.sh"
  echo "// Do NOT edit this file manually."
  echo "// Set the corresponding env var or Docker secret on the container instead."
  echo "window.__CONFIG__ = {"

  # ── Core ──────────────────────────────────────────────────────────────────
  printf '  VITE_TMDB_READ_API_KEY: %s,\n'  "$(js_val  "${VITE_TMDB_READ_API_KEY:-}"  "TMDB_READ_API_KEY")"
  printf '  VITE_CORS_PROXY_URL: %s,\n'     "$(js_val  "${VITE_CORS_PROXY_URL:-}"     "CORS_PROXY_URL")"
  printf '  VITE_M3U8_PROXY_URL: %s,\n'     "$(js_val  "${VITE_M3U8_PROXY_URL:-}"     "M3U8_PROXY_URL")"
  printf '  VITE_BACKEND_URL: %s,\n'        "$(js_val  "${VITE_BACKEND_URL:-}"         "BACKEND_URL")"
  printf '  VITE_DMCA_EMAIL: %s,\n'         "$(js_val  "${VITE_DMCA_EMAIL:-}"          "DMCA_EMAIL")"

  # ── Router / behaviour ────────────────────────────────────────────────────
  printf '  VITE_NORMAL_ROUTER: %s,\n'      "$(js_bool "${VITE_NORMAL_ROUTER:-false}"  "NORMAL_ROUTER")"
  printf '  VITE_ALLOW_AUTOPLAY: %s,\n'     "$(js_bool "${VITE_ALLOW_AUTOPLAY:-false}" "ALLOW_AUTOPLAY")"
  printf '  VITE_DISALLOWED_IDS: %s,\n'     "$(js_val  "${VITE_DISALLOWED_IDS:-}"      "DISALLOWED_IDS")"
  printf '  VITE_CDN_REPLACEMENTS: %s,\n'   "$(js_val  "${VITE_CDN_REPLACEMENTS:-}"    "CDN_REPLACEMENTS")"

  # ── Onboarding ────────────────────────────────────────────────────────────
  printf '  VITE_HAS_ONBOARDING: %s,\n'     "$(js_bool "${VITE_HAS_ONBOARDING:-false}" "HAS_ONBOARDING")"
  printf '  VITE_ONBOARDING_CHROME_EXTENSION_INSTALL_LINK: %s,\n' \
    "$(js_val "${VITE_ONBOARDING_CHROME_EXTENSION_INSTALL_LINK:-}" "ONBOARDING_CHROME_EXTENSION_INSTALL_LINK")"
  printf '  VITE_ONBOARDING_FIREFOX_EXTENSION_INSTALL_LINK: %s,\n' \
    "$(js_val "${VITE_ONBOARDING_FIREFOX_EXTENSION_INSTALL_LINK:-}" "ONBOARDING_FIREFOX_EXTENSION_INSTALL_LINK")"
  printf '  VITE_ONBOARDING_PROXY_INSTALL_LINK: %s,\n' \
    "$(js_val "${VITE_ONBOARDING_PROXY_INSTALL_LINK:-}" "ONBOARDING_PROXY_INSTALL_LINK")"
  printf '  VITE_HIDE_PROXY_ONBOARDING: %s,\n' \
    "$(js_bool "${VITE_HIDE_PROXY_ONBOARDING:-false}" "HIDE_PROXY_ONBOARDING")"

  # ── Optional features ─────────────────────────────────────────────────────
  printf '  VITE_ALLOW_FEBBOX_KEY: %s,\n'   "$(js_bool "${VITE_ALLOW_FEBBOX_KEY:-false}" "ALLOW_FEBBOX_KEY")"
  printf '  VITE_ALLOW_DEBRID_KEY: %s,\n'   "$(js_bool "${VITE_ALLOW_DEBRID_KEY:-false}" "ALLOW_DEBRID_KEY")"

  # ── Ads / banners ─────────────────────────────────────────────────────────
  printf '  VITE_SHOW_AD: %s,\n'            "$(js_bool "${VITE_SHOW_AD:-false}"          "SHOW_AD")"
  printf '  VITE_AD_CONTENT_URL: %s,\n'     "$(js_val  "${VITE_AD_CONTENT_URL:-}"        "AD_CONTENT_URL")"
  printf '  VITE_BANNER_MESSAGE: %s,\n'     "$(js_val  "${VITE_BANNER_MESSAGE:-}"        "BANNER_MESSAGE")"
  printf '  VITE_BANNER_ID: %s,\n'          "$(js_val  "${VITE_BANNER_ID:-}"             "BANNER_ID")"
  printf '  VITE_SHOW_SUPPORT_BAR: %s,\n'   "$(js_bool "${VITE_SHOW_SUPPORT_BAR:-false}" "SHOW_SUPPORT_BAR")"
  printf '  VITE_SUPPORT_BAR_VALUE: %s,\n'  "$(js_val  "${VITE_SUPPORT_BAR_VALUE:-}"     "SUPPORT_BAR_VALUE")"

  # ── Tracking ──────────────────────────────────────────────────────────────
  printf '  VITE_TRACK_SCRIPT: %s,\n'       "$(js_val  "${VITE_TRACK_SCRIPT:-}"          "TRACK_SCRIPT")"

  # ── Trakt ─────────────────────────────────────────────────────────────────
  printf '  VITE_USE_TRAKT: %s,\n'          "$(js_bool "${VITE_USE_TRAKT:-false}"         "USE_TRAKT")"
  printf '  VITE_TRAKT_CLIENT_ID: %s,\n'    "$(js_val  "${VITE_TRAKT_CLIENT_ID:-}"        "TRAKT_CLIENT_ID")"
  printf '  VITE_TRAKT_CLIENT_SECRET: %s,\n' \
    "$(js_val "${VITE_TRAKT_CLIENT_SECRET:-}" "TRAKT_CLIENT_SECRET")"
  printf '  VITE_TRAKT_REDIRECT_URI: %s,\n' \
    "$(js_val "${VITE_TRAKT_REDIRECT_URI:-}" "TRAKT_REDIRECT_URI")"

  echo "};"
} > "$CONFIG_FILE"

exec "$@"
