#!/bin/sh
# docker-entrypoint.sh
# Generates /usr/share/nginx/html/config.js from runtime environment variables,
# then execs the CMD (nginx). This lets a single Docker image be configured
# entirely at `docker run` time — no secrets are baked into image layers.
set -e

CONFIG_FILE="/usr/share/nginx/html/config.js"

# Output a JavaScript string literal, or null when the value is empty.
# Escapes backslashes and double-quotes so the output is valid JS.
js_val() {
  if [ -n "$1" ]; then
    printf '"%s"' "$(printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  else
    printf 'null'
  fi
}

# Output a JavaScript boolean literal (true/false).
js_bool() {
  case "$1" in
    true | 1 | yes) printf 'true' ;;
    *) printf 'false' ;;
  esac
}

{
  echo "// Runtime configuration — generated by docker-entrypoint.sh"
  echo "// Do NOT edit this file; set the corresponding env vars on the container instead."
  echo "window.__CONFIG__ = {"

  # ── Core ──────────────────────────────────────────────────────────────────
  printf '  VITE_TMDB_READ_API_KEY: %s,\n'  "$(js_val  "${VITE_TMDB_READ_API_KEY:-}")"
  printf '  VITE_CORS_PROXY_URL: %s,\n'     "$(js_val  "${VITE_CORS_PROXY_URL:-}")"
  printf '  VITE_M3U8_PROXY_URL: %s,\n'     "$(js_val  "${VITE_M3U8_PROXY_URL:-}")"
  printf '  VITE_BACKEND_URL: %s,\n'        "$(js_val  "${VITE_BACKEND_URL:-}")"
  printf '  VITE_DMCA_EMAIL: %s,\n'         "$(js_val  "${VITE_DMCA_EMAIL:-}")"

  # ── Router / behaviour ────────────────────────────────────────────────────
  printf '  VITE_NORMAL_ROUTER: %s,\n'      "$(js_bool "${VITE_NORMAL_ROUTER:-false}")"
  printf '  VITE_ALLOW_AUTOPLAY: %s,\n'     "$(js_bool "${VITE_ALLOW_AUTOPLAY:-false}")"
  printf '  VITE_DISALLOWED_IDS: %s,\n'     "$(js_val  "${VITE_DISALLOWED_IDS:-}")"
  printf '  VITE_CDN_REPLACEMENTS: %s,\n'   "$(js_val  "${VITE_CDN_REPLACEMENTS:-}")"

  # ── Onboarding ────────────────────────────────────────────────────────────
  printf '  VITE_HAS_ONBOARDING: %s,\n'     "$(js_bool "${VITE_HAS_ONBOARDING:-false}")"
  printf '  VITE_ONBOARDING_CHROME_EXTENSION_INSTALL_LINK: %s,\n' \
    "$(js_val "${VITE_ONBOARDING_CHROME_EXTENSION_INSTALL_LINK:-}")"
  printf '  VITE_ONBOARDING_FIREFOX_EXTENSION_INSTALL_LINK: %s,\n' \
    "$(js_val "${VITE_ONBOARDING_FIREFOX_EXTENSION_INSTALL_LINK:-}")"
  printf '  VITE_ONBOARDING_PROXY_INSTALL_LINK: %s,\n' \
    "$(js_val "${VITE_ONBOARDING_PROXY_INSTALL_LINK:-}")"
  printf '  VITE_HIDE_PROXY_ONBOARDING: %s,\n' "$(js_bool "${VITE_HIDE_PROXY_ONBOARDING:-false}")"

  # ── Optional features ─────────────────────────────────────────────────────
  printf '  VITE_ALLOW_FEBBOX_KEY: %s,\n'   "$(js_bool "${VITE_ALLOW_FEBBOX_KEY:-false}")"
  printf '  VITE_ALLOW_DEBRID_KEY: %s,\n'   "$(js_bool "${VITE_ALLOW_DEBRID_KEY:-false}")"

  # ── Ads / banners ─────────────────────────────────────────────────────────
  printf '  VITE_SHOW_AD: %s,\n'            "$(js_bool "${VITE_SHOW_AD:-false}")"
  printf '  VITE_AD_CONTENT_URL: %s,\n'     "$(js_val  "${VITE_AD_CONTENT_URL:-}")"
  printf '  VITE_BANNER_MESSAGE: %s,\n'     "$(js_val  "${VITE_BANNER_MESSAGE:-}")"
  printf '  VITE_BANNER_ID: %s,\n'          "$(js_val  "${VITE_BANNER_ID:-}")"
  printf '  VITE_SHOW_SUPPORT_BAR: %s,\n'   "$(js_bool "${VITE_SHOW_SUPPORT_BAR:-false}")"
  printf '  VITE_SUPPORT_BAR_VALUE: %s,\n'  "$(js_val  "${VITE_SUPPORT_BAR_VALUE:-}")"

  # ── Tracking ──────────────────────────────────────────────────────────────
  printf '  VITE_TRACK_SCRIPT: %s,\n'       "$(js_val  "${VITE_TRACK_SCRIPT:-}")"

  # ── Trakt ─────────────────────────────────────────────────────────────────
  printf '  VITE_USE_TRAKT: %s,\n'          "$(js_bool "${VITE_USE_TRAKT:-false}")"
  printf '  VITE_TRAKT_CLIENT_ID: %s,\n'    "$(js_val  "${VITE_TRAKT_CLIENT_ID:-}")"
  printf '  VITE_TRAKT_CLIENT_SECRET: %s,\n' "$(js_val "${VITE_TRAKT_CLIENT_SECRET:-}")"
  printf '  VITE_TRAKT_REDIRECT_URI: %s,\n' "$(js_val  "${VITE_TRAKT_REDIRECT_URI:-}")"

  echo "};"
} > "$CONFIG_FILE"

exec "$@"
